apiVersion: v1
kind: Namespace
metadata:
  name: gitlab

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitlab
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - image: gitlab/gitlab-ce:latest
        name: gitlab
        resources: 
         limits:
           memory: "1Gi"
           cpu: "1500m"
        imagePullPolicy: Always
        env:
        - name: GITLAB_ROOT_PASSWORD
          value: "PASSWORD"
        - name: EXTERNAL_URL
          value: "EXTERNALURL"
        volumeMounts:
        - name: gitlab
          mountPath: /var/log/gitlab
          subPath: log
        - name: gitlab
          mountPath: /etc/gitlab
          subPath: etc
        - name: gitlab
          mountPath: /var/opt/gitlab
          subPath: var
        ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 80
            protocol: TCP
          - containerPort: 22
            protocol: TCP            
      volumes:
      - name: gitlab
        persistentVolumeClaim:
          claimName: gitlab-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

--- 

apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: gitlab
  ports:
    - name: https
      port: 443
      targetPort: 443
      nodePort: 31043
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31080
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 31022